package train.trip.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import train.trip.mbg.entity.DepArrInfo;
import train.trip.mbg.entity.DepArrInfoExample;

public interface DepArrInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	long countByExample(DepArrInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	int deleteByExample(DepArrInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	@Delete({ "delete from dep_arr_info", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	@Insert({ "insert into dep_arr_info (id, schedule_id, ", "dep_arr_time, station_name, ", "dep_arr)",
			"values (#{id,jdbcType=INTEGER}, #{scheduleId,jdbcType=INTEGER}, ",
			"#{depArrTime,jdbcType=TIME}, #{stationName,jdbcType=VARCHAR}, ", "#{depArr,jdbcType=CHAR})" })
	int insert(DepArrInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	int insertSelective(DepArrInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	List<DepArrInfo> selectByExample(DepArrInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	@Select({ "select", "id, schedule_id, dep_arr_time, station_name, dep_arr", "from dep_arr_info",
			"where id = #{id,jdbcType=INTEGER}" })
	@ResultMap("train.trip.mbg.mapper.DepArrInfoMapper.BaseResultMap")
	DepArrInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") DepArrInfo record, @Param("example") DepArrInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") DepArrInfo record, @Param("example") DepArrInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(DepArrInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dep_arr_info
	 * @mbg.generated
	 */
	@Update({ "update dep_arr_info", "set schedule_id = #{scheduleId,jdbcType=INTEGER},",
			"dep_arr_time = #{depArrTime,jdbcType=TIME},", "station_name = #{stationName,jdbcType=VARCHAR},",
			"dep_arr = #{depArr,jdbcType=CHAR}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(DepArrInfo record);
}