package train.trip.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import train.trip.mbg.entity.Schedule;
import train.trip.mbg.entity.ScheduleExample;

public interface ScheduleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	long countByExample(ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	int deleteByExample(ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	@Delete({ "delete from schedule", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	@Options(useGeneratedKeys=true, keyProperty="id")
	@Insert({ "insert into schedule (id, train_trip_id, ", "day_number, train_name, ", "action)",
			"values (#{id,jdbcType=INTEGER}, #{trainTripId,jdbcType=INTEGER}, ",
			"#{dayNumber,jdbcType=INTEGER}, #{trainName,jdbcType=VARCHAR}, ", "#{action,jdbcType=VARCHAR})" })
	int insert(Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	int insertSelective(Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	List<Schedule> selectByExample(ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	@Select({ "select", "id, train_trip_id, day_number, train_name, action", "from schedule",
			"where id = #{id,jdbcType=INTEGER}" })
	@ResultMap("train.trip.mbg.mapper.ScheduleMapper.BaseResultMap")
	Schedule selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") Schedule record, @Param("example") ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") Schedule record, @Param("example") ScheduleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Schedule record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	@Update({ "update schedule", "set train_trip_id = #{trainTripId,jdbcType=INTEGER},",
			"day_number = #{dayNumber,jdbcType=INTEGER},", "train_name = #{trainName,jdbcType=VARCHAR},",
			"action = #{action,jdbcType=VARCHAR}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Schedule record);
}