package train.trip.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import train.trip.mbg.entity.TrainTrip;
import train.trip.mbg.entity.TrainTripExample;

public interface TrainTripMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	long countByExample(TrainTripExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	int deleteByExample(TrainTripExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	@Delete({ "delete from train_trip", "where id = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	@Insert({ "insert into train_trip (id, value, ", "departure_date, note)",
			"values (#{id,jdbcType=INTEGER}, #{value,jdbcType=VARCHAR}, ",
			"#{departureDate,jdbcType=TIMESTAMP}, #{note,jdbcType=LONGVARCHAR})" })
	int insert(TrainTrip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	int insertSelective(TrainTrip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	List<TrainTrip> selectByExampleWithBLOBs(TrainTripExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	List<TrainTrip> selectByExample(TrainTripExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	@Select({ "select", "id, value, departure_date, note", "from train_trip", "where id = #{id,jdbcType=INTEGER}" })
	@ResultMap("train.trip.mbg.mapper.TrainTripMapper.ResultMapWithBLOBs")
	TrainTrip selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") TrainTrip record, @Param("example") TrainTripExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	int updateByExampleWithBLOBs(@Param("record") TrainTrip record, @Param("example") TrainTripExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") TrainTrip record, @Param("example") TrainTripExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TrainTrip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	@Update({ "update train_trip", "set value = #{value,jdbcType=VARCHAR},",
			"departure_date = #{departureDate,jdbcType=TIMESTAMP},", "note = #{note,jdbcType=LONGVARCHAR}",
			"where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKeyWithBLOBs(TrainTrip record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table train_trip
	 * @mbg.generated
	 */
	@Update({ "update train_trip", "set value = #{value,jdbcType=VARCHAR},",
			"departure_date = #{departureDate,jdbcType=TIMESTAMP}", "where id = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(TrainTrip record);
}