package train.trip.mbg.entity;

public class Schedule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.train_trip_id
	 * @mbg.generated
	 */
	private Integer trainTripId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.day_number
	 * @mbg.generated
	 */
	private Integer dayNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.train_name
	 * @mbg.generated
	 */
	private String trainName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column schedule.action
	 * @mbg.generated
	 */
	private String action;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.id
	 * @return  the value of schedule.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.id
	 * @param id  the value for schedule.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.train_trip_id
	 * @return  the value of schedule.train_trip_id
	 * @mbg.generated
	 */
	public Integer getTrainTripId() {
		return trainTripId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.train_trip_id
	 * @param trainTripId  the value for schedule.train_trip_id
	 * @mbg.generated
	 */
	public void setTrainTripId(Integer trainTripId) {
		this.trainTripId = trainTripId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.day_number
	 * @return  the value of schedule.day_number
	 * @mbg.generated
	 */
	public Integer getDayNumber() {
		return dayNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.day_number
	 * @param dayNumber  the value for schedule.day_number
	 * @mbg.generated
	 */
	public void setDayNumber(Integer dayNumber) {
		this.dayNumber = dayNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.train_name
	 * @return  the value of schedule.train_name
	 * @mbg.generated
	 */
	public String getTrainName() {
		return trainName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.train_name
	 * @param trainName  the value for schedule.train_name
	 * @mbg.generated
	 */
	public void setTrainName(String trainName) {
		this.trainName = trainName == null ? null : trainName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column schedule.action
	 * @return  the value of schedule.action
	 * @mbg.generated
	 */
	public String getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column schedule.action
	 * @param action  the value for schedule.action
	 * @mbg.generated
	 */
	public void setAction(String action) {
		this.action = action == null ? null : action.trim();
	}
}