package train.trip.mbg.entity;

import java.util.ArrayList;
import java.util.List;

public class ScheduleExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule
	 * @mbg.generated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule
	 * @mbg.generated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table schedule
	 * @mbg.generated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	public ScheduleExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table schedule
	 * @mbg.generated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table schedule
	 * @mbg.generated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdIsNull() {
			addCriterion("train_trip_id is null");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdIsNotNull() {
			addCriterion("train_trip_id is not null");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdEqualTo(Integer value) {
			addCriterion("train_trip_id =", value, "trainTripId");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdNotEqualTo(Integer value) {
			addCriterion("train_trip_id <>", value, "trainTripId");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdGreaterThan(Integer value) {
			addCriterion("train_trip_id >", value, "trainTripId");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("train_trip_id >=", value, "trainTripId");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdLessThan(Integer value) {
			addCriterion("train_trip_id <", value, "trainTripId");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdLessThanOrEqualTo(Integer value) {
			addCriterion("train_trip_id <=", value, "trainTripId");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdIn(List<Integer> values) {
			addCriterion("train_trip_id in", values, "trainTripId");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdNotIn(List<Integer> values) {
			addCriterion("train_trip_id not in", values, "trainTripId");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdBetween(Integer value1, Integer value2) {
			addCriterion("train_trip_id between", value1, value2, "trainTripId");
			return (Criteria) this;
		}

		public Criteria andTrainTripIdNotBetween(Integer value1, Integer value2) {
			addCriterion("train_trip_id not between", value1, value2, "trainTripId");
			return (Criteria) this;
		}

		public Criteria andDayNumberIsNull() {
			addCriterion("day_number is null");
			return (Criteria) this;
		}

		public Criteria andDayNumberIsNotNull() {
			addCriterion("day_number is not null");
			return (Criteria) this;
		}

		public Criteria andDayNumberEqualTo(Integer value) {
			addCriterion("day_number =", value, "dayNumber");
			return (Criteria) this;
		}

		public Criteria andDayNumberNotEqualTo(Integer value) {
			addCriterion("day_number <>", value, "dayNumber");
			return (Criteria) this;
		}

		public Criteria andDayNumberGreaterThan(Integer value) {
			addCriterion("day_number >", value, "dayNumber");
			return (Criteria) this;
		}

		public Criteria andDayNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("day_number >=", value, "dayNumber");
			return (Criteria) this;
		}

		public Criteria andDayNumberLessThan(Integer value) {
			addCriterion("day_number <", value, "dayNumber");
			return (Criteria) this;
		}

		public Criteria andDayNumberLessThanOrEqualTo(Integer value) {
			addCriterion("day_number <=", value, "dayNumber");
			return (Criteria) this;
		}

		public Criteria andDayNumberIn(List<Integer> values) {
			addCriterion("day_number in", values, "dayNumber");
			return (Criteria) this;
		}

		public Criteria andDayNumberNotIn(List<Integer> values) {
			addCriterion("day_number not in", values, "dayNumber");
			return (Criteria) this;
		}

		public Criteria andDayNumberBetween(Integer value1, Integer value2) {
			addCriterion("day_number between", value1, value2, "dayNumber");
			return (Criteria) this;
		}

		public Criteria andDayNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("day_number not between", value1, value2, "dayNumber");
			return (Criteria) this;
		}

		public Criteria andTrainNameIsNull() {
			addCriterion("train_name is null");
			return (Criteria) this;
		}

		public Criteria andTrainNameIsNotNull() {
			addCriterion("train_name is not null");
			return (Criteria) this;
		}

		public Criteria andTrainNameEqualTo(String value) {
			addCriterion("train_name =", value, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameNotEqualTo(String value) {
			addCriterion("train_name <>", value, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameGreaterThan(String value) {
			addCriterion("train_name >", value, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameGreaterThanOrEqualTo(String value) {
			addCriterion("train_name >=", value, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameLessThan(String value) {
			addCriterion("train_name <", value, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameLessThanOrEqualTo(String value) {
			addCriterion("train_name <=", value, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameLike(String value) {
			addCriterion("train_name like", value, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameNotLike(String value) {
			addCriterion("train_name not like", value, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameIn(List<String> values) {
			addCriterion("train_name in", values, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameNotIn(List<String> values) {
			addCriterion("train_name not in", values, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameBetween(String value1, String value2) {
			addCriterion("train_name between", value1, value2, "trainName");
			return (Criteria) this;
		}

		public Criteria andTrainNameNotBetween(String value1, String value2) {
			addCriterion("train_name not between", value1, value2, "trainName");
			return (Criteria) this;
		}

		public Criteria andActionIsNull() {
			addCriterion("action is null");
			return (Criteria) this;
		}

		public Criteria andActionIsNotNull() {
			addCriterion("action is not null");
			return (Criteria) this;
		}

		public Criteria andActionEqualTo(String value) {
			addCriterion("action =", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotEqualTo(String value) {
			addCriterion("action <>", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThan(String value) {
			addCriterion("action >", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionGreaterThanOrEqualTo(String value) {
			addCriterion("action >=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThan(String value) {
			addCriterion("action <", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLessThanOrEqualTo(String value) {
			addCriterion("action <=", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionLike(String value) {
			addCriterion("action like", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotLike(String value) {
			addCriterion("action not like", value, "action");
			return (Criteria) this;
		}

		public Criteria andActionIn(List<String> values) {
			addCriterion("action in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotIn(List<String> values) {
			addCriterion("action not in", values, "action");
			return (Criteria) this;
		}

		public Criteria andActionBetween(String value1, String value2) {
			addCriterion("action between", value1, value2, "action");
			return (Criteria) this;
		}

		public Criteria andActionNotBetween(String value1, String value2) {
			addCriterion("action not between", value1, value2, "action");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table schedule
	 * @mbg.generated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table schedule
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}