package train.trip.mbg.entity;

import java.util.Date;

public class TrainTrip {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column train_trip.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column train_trip.value
	 * @mbg.generated
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column train_trip.departure_date
	 * @mbg.generated
	 */
	private Date departureDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column train_trip.note
	 * @mbg.generated
	 */
	private String note;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column train_trip.id
	 * @return  the value of train_trip.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column train_trip.id
	 * @param id  the value for train_trip.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column train_trip.value
	 * @return  the value of train_trip.value
	 * @mbg.generated
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column train_trip.value
	 * @param value  the value for train_trip.value
	 * @mbg.generated
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column train_trip.departure_date
	 * @return  the value of train_trip.departure_date
	 * @mbg.generated
	 */
	public Date getDepartureDate() {
		return departureDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column train_trip.departure_date
	 * @param departureDate  the value for train_trip.departure_date
	 * @mbg.generated
	 */
	public void setDepartureDate(Date departureDate) {
		this.departureDate = departureDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column train_trip.note
	 * @return  the value of train_trip.note
	 * @mbg.generated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column train_trip.note
	 * @param note  the value for train_trip.note
	 * @mbg.generated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}
}